[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.default.zksync]
enabled = true

fs_permissions= [{access="read-write", path="script/target"},{access="read",path="broadcast"},{access="read-write", path="signature.txt"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
